### ISSUE TITLE
HTML Syntax highlighting not working properly

### ISSUE THREAD

**Issue by fedoranimus** [aurelia/vscode-extension#10]
**I'm submitting a bug report**

* **Library Version:**
0.1.5

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.3.0

* **NPM Version:**
3.10.5

* **Language:**
TypeScript 2.0

**Current behavior:**
![image](https://cloud.githubusercontent.com/assets/179260/19558540/1bca77b2-9699-11e6-92c8-79031b2d8677.png)

**Expected/desired behavior:**
Standard HTML Syntax highlighting

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
Have usable HTML Syntax Highlighting

**Comment by EisenbergEffect** [comment]
@eriklieben I've observed this above in the same code that I reported the completion errors on.

**Comment by eriklieben** [comment]
Thanks for the bug report, I am sorry you are experiencing these issues.

This bug is resolved in version 0.1.6. I have some problems with the publishing tools for vscode to get the extension in the marketplace, which cause a bit of a delay in getting the latest version in the marketplace.

If you really need the functionality (and could not wait) you could install it manually, but I think this requires you to de-install it again later on to receive further updates that are published to the marketplace, so it's not the preferred way to install the plugin. You could do this by getting the .vsix file from https://github.com/aurelia/vscode-extension/releases/tag/0.1.6 and perform the following command:

```
code --install-extension aurelia-0.1.6.vsix
```

**Comment by eriklieben** [comment]
Version 0.1.7 is released, which also includes the fixes. Can you upgrade to 0.1.7 and restart vscode to see if you still have the same issues?

Thanks

**Comment by fedoranimus** [comment]
I just updated to v0.1.7 and the issues are resolved.

![image](https://cloud.githubusercontent.com/assets/179260/19649058/564941ac-99d2-11e6-854e-31fe4b39cd24.png)

**Comment by eriklieben** [comment]
Fantastic, thanks for confirming.
