### ISSUE TITLE
MacOS Fan Issue

### ISSUE THREAD

**Issue by jamesond** [aurelia/vscode-extension#155]
****
I'm submitting a bug report

* **Extension Version:**
2.0.6

**Please tell us about your environment:**
* **Operating System:**
OSX 11.2.3 Big Sur

* **Visual studio code version:**
1.55.0

**Screenshot of incorrect highlight**

**HTML/JS/TS of incorrect highlight**

**Current behavior:**

**Expected/desired behavior:**
Normal CPU Usage
When I enable the Aurelia extension the "Code Helper (Renderer)" process name goes well above 100% and my fans kick on full blast. I turn the extension back off and the fans go down.

* **What is the expected behavior?**
* 
See above.

* **What is the motivation / use case for changing the behavior?**

**Comment by hiaux0** [comment]
_Sry, I missed the notification for this :(_

Could you share some insights to your project structure?
Might be, that there is a misbehavior in parsing.

1. Enable extension
2. open output (choose Aurelia v2)
3. Check for sensible information
4. If possible share

FYI: If v2 is unusable due to this, you can always [revert to v1.0.7](https://github.com/aurelia/vscode-extension/issues/154#issuecomment-803478131)

**Comment by Alexander-Taran** [comment]
```
async triageQuestion(id) =>{
 respondSameDay()
 let response = await getResponseFromOP( { timeout : 4weeks } )
 if(!response) {
    closeQuestion(id,randomReason())
 }
}
```

**Comment by hiaux0** [comment]
Closed due to insufficient steps to repro.
Perf issues are always welcomed though!
