### ISSUE TITLE
Unclear what the auto-complete can complete

### ISSUE THREAD

**Issue by krokofant** [aurelia/vscode-extension#22]
In the GIF in the marketplace and README it's unclear what kinds of autocomplete is supported. The GIF shows support for events and attribute stuff but it also shows insertion of *variables and function names*.

Is this supported?

macOS 10.11.6
VSCode: 1.7.1
extension-version: 0.1.9
langugage: TypeScript

![](https://raw.githubusercontent.com/aurelia/vscode-extension/master/images/aurelia-autocomplete.gif)

**Comment by eriklieben** [comment]
Sorry, I need to update that gif and match it with the current state.

(The insertion of variables and functions are typed by hand in the above gif, just speeded up to make the gif smaller, but I see why that is causing confusion.)

Somewhere between version 1.5 and 1.6 of vs code the implementation you see above stopped working due to changes in how vs code handles things (I guess, the plugin code didn't change).

I quickly rewrote everything to be a background language service to get suggest working again. This means it offloads autocomplete to another process. I used the same behaviour as the current HTML suggest (the default), which fixed another issue that it wasn't placing your cursor inside the "" after completion.

Currently, it will suggest the full attribute, so for example value.bind="" instead of .bind after you type value. And it's a bit smarter about what it suggest (knows when events bubble), so for example:

mouseover an event that bubbles suggests:

```
mouseover.delegate=""
mouseover.trigger=""
mouseover.call=""
```

mouseenter an event that doesn't bubble suggests:
```
mouseenter.trigger=""
mouseenter.call=""
```

It won't do this on custom elements for now, I am working on code to improve that. So in the future it will figure out what the bindings are of your custom element and provide those, together with the default attributes.

**Comment by eriklieben** [comment]
I have completely rewritten the auto complete functionality as of version 0.3.0 and started documenting it over here https://github.com/aurelia/vscode-extension/wiki/Autocomplete.

(The support for typing a dot after an attribute is back working again, as it was in the gif animation)
