### ISSUE TITLE
Latest vscode insiders breaks the Aurelia Dark+ theme (braces are black)

### ISSUE THREAD

**Issue by eamodio** [aurelia/vscode-extension#31]
**I'm submitting a bug report**

* **Extension Version:**
0.2.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.2

* **Visual studio code version:**
1.9.0-insider 31997b32c354b0531f296379cec364b094ee362d

**Screenshot of incorrect highlight**
![screen shot 2017-01-10 at 8 51 23 am](https://cloud.githubusercontent.com/assets/641685/21808624/118be402-d712-11e6-8619-8b5852de7c55.png)

**Screenshot of Visual Studio Dark+**
![image](https://cloud.githubusercontent.com/assets/641685/21808676/4f93fc30-d712-11e6-9ea2-97fca3daeb15.png)

**Comment by eriklieben** [comment]
Thanks for the bug report!

I will look into this and check if we could release a new version that resolves this, but doesn't break the current production version of vscode.

For now (If the current situation makes it unusable for you), a quick fix would be to do this:

Open up the file 

```C:\Users\erik.lieben\.vscode-insiders\extensions\AureliaEffect.aurelia-0.2.0\themes\dark_vs.json```
(will be on a different location on mac, I guess in your home / user folder)

Replace (on top of the file)

```
{
	"name": "Dark Visual Studio",
	"settings": [
		{
			"scope": "emphasis",
```

With
```
{
	"name": "Dark Visual Studio",
	"settings": [
		{
			"settings": {
				"foreground": "#D4D4D4",
				"background": "#1E1E1E"
			}
		},
		{
			"scope": "emphasis",
```
and reload vscode. 

I did not test this fully yet, only looked for 5 minutes at it, because I don't have more time at the moment. So might not be a full fix, but it looks like it works.

**Comment by eamodio** [comment]
@eriklieben thanks! No worries on the quick fix -- I just mainly wanted to file this as a heads-up

**Comment by eriklieben** [comment]
Fixed in 0.2.1

Still looking at why the syntax highlighting of aurelia elements in purple is broken.
Can't find yet what they modified in vscode 1.9.0 that breaks this.

**Comment by maroy1986** [comment]
That fix the black bracket but now the aurelia keywords in HTML code aren't purple highlight anymore.

**Comment by eriklieben** [comment]
v0.2.2 fixes this.

They changed the way styles work for vscode. In version 1.8.0 and lower it would inherit a style rule . So setting "html.au" to purple would color all the separate items. In 1.9.0 of vscode we now need to specify all the tags separate like "compose.html.au", "router-view.html.au" to color purple.

**Comment by maroy1986** [comment]
Wow that was fast! I confirm that v.0.2.2 fix the issue :) Thanks!
