### ISSUE TITLE
New setting to be able to provde inclusion or exclusion globs (dirs/files)

### ISSUE THREAD

**Issue by diegohb** [aurelia/vscode-extension#49]
It's currently showing html problems reported for files inside of node_modules where innerHTML.bind="" in some files.

![image](https://user-images.githubusercontent.com/3726681/29468903-1d292810-8414-11e7-88d6-e1018b4ea872.png)

**Comment by eriklieben** [comment]
Thank you very much for submitting an issue.

I will look into this. 
I am not sure if it should even give a warning about ```innerHTML`.bind=""``` that might be a bug.

**Comment by eriklieben** [comment]
As a reference for myself, this should make use of the attribute map to get the correct case:

https://github.com/aurelia/templating-binding/blob/master/src/attribute-map.js#L16

**Comment by eriklieben** [comment]
https://github.com/aurelia/vscode-extension/issues/54 fixes the above warnings (allows innerHTML because it is allowed) and resolves your current issue.

The mechanism used to provide these hints is called Code Actions. I think disabling this to a specific folder or path is functionality that should be implemented by the VSCode team generic for all VSCode extensions and not inside of an extension.
