### ISSUE TITLE
AutoComplete and Command Palette does not work on MAC OS

### ISSUE THREAD

**Issue by shahabganji** [aurelia/vscode-extension#9]
**I'm submitting a bug report**

* **Library Version:**
0.1.5

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12 macOS Sierra

* **Node Version:**
6.2.2

* **NPM Version:**
3.9.5

* **Language:**
TypeScript 2.0.3

**Current behavior:**

Just syntax highlighter works, and I have no autocompletion and command palette support. 
I will get command palette support if I install ```Aurelia-CLI command``` but still no code completion.

**Comment by eriklieben** [comment]
Thanks for submitting an issue. I am sorry for the inconvenience.

I discovered that since version 1.6.0 of vscode the autocomplete stopped working (issue #7). It now only works if you type part of it so ```value.b``` will only activate it.

I already planned to move the autocomplete functionality to a language server to allow it to do more and make it perform better. Currently, I am working on that in the branch [language-server](https://github.com/aurelia/vscode-extension/tree/language-server). Will probably be ready somewhere this week depending on how much spare time I have.

It will function a bit differently (to also resolve #4), here is an early sample: [sample video of new autocomplete](https://youtu.be/XpqbESIVEJg). Still a bit buggy/ requires some more work, but this is more like how the included HTML autocomplete in vscode works.

Separately from that, I will need to look into why it isn't installing aurelia-cli. It is set as a dependency, but somehow not installed I guess.

**Comment by shahabganji** [comment]
I am very thankful to you for your complete and prompt response. 

About the last part of your answer which is about aurelia-cli, actually I meant the aurelia extension does not have the au commands such as ```au new``` or ```au build``` until I manually added aurelia-cli extension

**Comment by eriklieben** [comment]
Can you try to install version 0.1.7 and see if the issues still occur? Autocompletion works a bit different, but should autocomplete full attributes, so for example "if" can autocomplete to ```if.bind=""```.

Thanks

**Comment by shahabganji** [comment]
Dear @eriklieben ,
I've tried version 0.1.8 and it sounds that it is working properly. I will do extra checks the next day and if any problem exists I'll let you know.

Thanks for your time and support
